### ISSUE TITLE
[Feature] pdf viewer supports

### ISSUE THREAD

**Issue by xyecoding** [jakewvincent/texmagic.nvim#2]
It will be awesome to support pdf viewers with forward and backword search.

**Comment by jakewvincent** [comment]
> It will be awesome to support pdf viewers with forward and backword search.

Hi @xyegithub, since the purpose of this plug-in is only to pass any arbitrary build engine information you specify in your config to the Texlab language server or something similar, your request is outside of the scope of this plug-in.

However, if you're using Texlab, what you're looking for should be possible to achieve in your Texlab config. You might want to take a look at [this config](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/texlab.lua) for an example, and if you're having trouble getting Texlab to do forward and backward search, consider checking out Texlab's documentation [here](https://github.com/latex-lsp/texlab/blob/master/docs/options.md) or filing an issue on their GitHub page.

**Comment by xyecoding** [comment]
> > It will be awesome to support pdf viewers with forward and backword search.
> 
> Hi @xyegithub, since the purpose of this plug-in is only to pass any arbitrary build engine information you specify in your config to the Texlab language server or something similar, your request is outside of the scope of this plug-in.
> 
> However, if you're using Texlab, what you're looking for should be possible to achieve in your Texlab config. You might want to take a look at [this config](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/texlab.lua) for an example, and if you're having trouble getting Texlab to do forward and backward search, consider checking out Texlab's documentation [here](https://github.com/latex-lsp/texlab/blob/master/docs/options.md) or filing an issue on their GitHub page.

OK! Thanks!
